### ISSUE TITLE
001 - The app chashes with the updated data.txt

### ISSUE THREAD

**Issue by ilyapavlovdx** [doichenzeldaten/DataGrid#2]
Hi,
I get an exception when opening the new data file in your app.
![image](https://user-images.githubusercontent.com/26572971/60765816-e812b200-a0a8-11e9-8166-33981634472c.png)

This file is still valid JSON - you can check it on you side by defining a variable in the browser console (F12).
![image](https://user-images.githubusercontent.com/26572971/60765855-7850f700-a0a9-11e9-9d54-91d17b25b719.png)

As you can see, the browser parses it properly.
![image](https://user-images.githubusercontent.com/26572971/60765861-9f0f2d80-a0a9-11e9-85ef-b3938aa3f60e.png)

**Comment by AlexanderSharygin** [comment]
Fixed.
![Без названия (1)](https://user-images.githubusercontent.com/52005798/60903346-cfa5c180-a279-11e9-8d15-9d74319ed069.png)
![Без названия](https://user-images.githubusercontent.com/52005798/60903358-d46a7580-a279-11e9-9817-8ea85b6adcf1.png)

**Comment by ilyapavlovdx** [comment]
ок
