### ISSUE TITLE
Allow a user to choose columns that will be displayed

### ISSUE THREAD

**Issue by ilyapavlovdx** [doichenzeldaten/DataGrid#3]
Hi,
A user should be able to choose columns to display. When he/she selects specific columns, the app displays corresponding column data in tabular format.

We don't have specific requirements regarding the command line UI, so create it by yourself. However, note that it's a bad idea to ask the user to type full column names in console.

**Comment by AlexanderSharygin** [comment]
Fixed.
Feature is implemented.
A user able to choose columns to display. 
When user selecting specific columns, the app displays corresponding column data in tabular format.

**Comment by ilyapavlovdx** [comment]
OK, your implementation is acceptable. Our next task is to make the UI more intuitive.

Here is my requirement.

**(first, refer to the attached video [menu.zip](https://github.com/doichenzeldaten/DataGrid/files/3448971/menu.zip))**

Once the program starts, a user sees the following UI.

[ ] FirstName (this row is colored blue)
[ ] LastName
[ ] ... etc.

[ ] - before a field name is a check mark. It is empty in all items by default. The user should be able to check specific items by pressing Space, and the mark should become [x].

For example, the first two items are selected and will be displayed in the output when a user presses Enter.
[x] FirstName
[x] LastName
[ ] ... etc.

You also need to implement the item focusing logic. Take note of the '(this row is colored blue)'. A user should be able to focus an item by pressing Up/Down, and the item should be colored. For example, the second item is focused in the sample below.
[ ] FirstName
[ ] LastName (this row is colored blue)
[ ] ... etc.
Now, when user presses Space, the second item will be checked.
[ ] FirstName
[x] LastName (this row is colored blue)
[ ] ... etc.
Similarly, the user can navigate to any item and toggle its checked state by pressing Enter.

Note that you should refresh the existing information instead of printing everything multiple times on the console. 

P.S. See Console routines at https://docs.microsoft.com/en-us/dotnet/api/system.console?view=netframework-4.8

**Comment by ilyapavlovdx** [comment]
Don't look at ??????????? - it's the issue with my encoding. However, the rest looks bad.
![image](https://user-images.githubusercontent.com/26572971/62459642-9d0fbb80-b788-11e9-9c80-7f0321d2fc49.png)

Besides,
I don't want to input any text to work with UI. I need to be able to continue navigating through the menu and check/uncheck items after pressing Enter. So don't ask me to press Y or N. Just keep me in the initial menu.

**Comment by AlexanderSharygin** [comment]
Fixed. All looks good now.
![1147dc318d](https://user-images.githubusercontent.com/52005798/62654259-10bbef00-b968-11e9-9cb4-c822946f9d5c.jpg)
