### ISSUE TITLE
Include data.txt into the project

### ISSUE THREAD

**Issue by ilyapavlovdx** [doichenzeldaten/DataGrid#4]
Hey, 
I'm tired of the necessetity of copying damn data.txt to bin/Debug every time I download your project. Yeah, I'm just pressing 'Open in Visual Studio' on hithub and not storing my local copy. So I'm requesting your project to work without additional manipulations on my side. Schneller!

P.S. It's the way to you to start with Visual Studio features. Follow https://trello.com/c/eT8vADDZ/8-visual-studio

**Comment by AlexanderSharygin** [comment]
Fixed. Input text file is now located in the "Files" subdirectory which is located in project directory.

**Comment by ilyapavlovdx** [comment]
It's OK to see the file in a separate folder. But the way you implemented it is incorrect. You hardcoded bin\Debug in your path. 
https://github.com/doichenzeldaten/DataGrid/blob/e84a64c5d67ddea0e4fd8fdc0868d58f9a00080e/Parser/Program.cs#L14
What if I move out the .exe from the Debug?
